name: Template Release
on:
  push:
    branches:
      - main
jobs:
  release:
    permissions:
      contents: write
      packages: write
      releases: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release of /template folder
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: Template Release
          tag: template
          body: Template Release
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          draft: false
          prerelease: false
          artifacts: "./template"
          artifactContentType: application/zip
          replacesArtifacts: true
