name: Template Release
on:
  push:
    branches:
      - main
jobs:
  release:
    permissions:
      contents: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Compress template
        run: |
          tar -czvf template.tar.gz template
      - name: Upload template
        uses: actions/upload-artifact@v4
        with:
          name: template
          path: template.tar.gz
